-- SELECT
-- FROM DUAL
-- CONNCET BY LEVEL <= 100000

-- 조회
SELECT *
  FROM GROUPTABLE
 WHERE 1=1
   AND TEST_GROUP = 'GROUP_1'
ORDER BY STB_ID;
 
-- 100000 ROW INSERT
INSERT INTO GROUPTABLE (
    CUST_ID,
    STB_ID,
    USE_YN,
    USER_NM,
    TEST_GROUP,
)
SELECT 
    '123123',
    '{999999' || lpad(level, 6, '0') || '}',
    'Y',
    'ADMIN',
    'GROUP_1',
FROM DUAL CONNECT BY LEVEL <=100000;

-- 삭제
DELETE FROM GROUPTABLE
WHERE 1=1
  AND CUST_ID = '123123'
  AND USER_NM = 'ADMIN'
  AND TEST_GROUP = 'GROUP_1';